---

plugins:
    - babel
    - jest

env:
    node: true
    browser: true
    jest: true

parser: babel-eslint

extends:
    - 'airbnb-base'
    - 'plugin:react/recommended'

rules:
    no-console: 0
    react/jsx-indent: ["error", 2]

settings:
    react:
        version: 'detect'
    import/resolver:
        - node
        - webpack
